pipeline {
    agent any

    tools {
        go 'go-1.24.6'
        git 'git'
    }

    parameters {
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Choose environment')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build \
                -t app:${params.ENV} \
                -f app/Dockerfile .
                """
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build \
                  -t app:${params.ENV} \
                  -f app/Dockerfile .
                """
            }
        }
    }

    post {
        always {
            echo "Cleaning up Docker images..."
            sh "docker rmi -f app:${params.ENV}"
        }
    }
}
