def REGISTRY = "registry.kube-system.svc.cluster.local:80"

pipeline {
    agent any

    tools {
        go 'go-1.24.6'
        git 'git'
    }

    parameters {
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Choose environment')
    }

    stages {
        stage('Checkout') {
            steps {
                sh 'rm -rf *'
                checkout scm
            }
        }

        stage('Build Go App') {
            steps {
                sh """
                mkdir -p bin
                cd app
                go mod tidy
                GOOS=linux GOARCH=amd64 go build -o ../bin/app main.go
                """
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                docker build \
                  -t app:${params.ENV} \
                  -f app/Dockerfile .

                docker tag app:${params.ENV} ${REGISTRY}/app:${params.ENV}
                docker push ${REGISTRY}/app:${params.ENV}
                """
            }
        }

        // stage('Tests') {
        //     steps {
        //         sh """
        //             go test
        //         """
        //     }
        // }

        stage('Deploy') {
            steps {
                sh """
                    helm upgrade --install \
                    -f ./app/helm/values.yaml \
                    --set image.repository=${REGISTRY}/app \
                    --set image.tag=${params.ENV} go-app-${params.ENV} ./helm/app --namespace ${params.ENV} \
                    --recreate-pods
                """
            }
        }
    }

    post {
        always {
            echo "Cleaning up Docker images..."
            sh "docker rmi -f app:${params.ENV}"
        }
    }
}